export enum IconsTypes {
  LOGO = 'logo',
  CART = 'cart',
  SEARCH = 'search',
  ARROW_DOWN = 'arrow-down',
  PROFILE = 'profile',
  STAR = 'star',
  STAR_EMPTY = 'star-empty',
  HEART = 'heart',
  ERROR = 'error',
  CHECK_MARK = 'check-mark',
  FILTER = 'filter',
  CLOSE = 'close',
  ORDER_ASC = 'order-asc',
  ORDER_DESC = 'order-desc',
}
